name: 极简镜像下载器

on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '输入镜像名（用英文逗号分隔）'
        required: true
        default: 'pennlinc/qsiprep:1.0.0'

jobs:
  download:
    runs-on: ubuntu-latest  # 自动使用最新系统获取最大空间
    steps:
      - name: 下载并切割镜像
        run: |
          # 自动清理旧文件
          docker system prune -af
          sudo rm -rf /var/lib/docker/tmp/*

          # 一键分卷处理（自动处理所有镜像）
          echo "${{ github.event.inputs.docker_images }}" | tr ',' '\n' | while read image; do
            docker pull --platform linux/amd64 "$image"
            safe_name=$(echo "$image" | tr '/:' '__')
            docker save "$image" | gzip | split -b 1500M - "${safe_name}.part."
            docker rmi "$image"
          done

      - name: 上传分卷包
        uses: actions/upload-artifact@v4
        with:
          name: 切割好的镜像包
          path: |
            *.part.*
          retention-days: 1
