name: x86-64 Pull and Save Docker Image
on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '输入镜像名称（英文逗号分隔）'
        required: true
        default: 'alpine:latest,busybox:stable-glibc'

jobs:
  pull_and_package:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean up Docker
        run: |
          docker system prune -a -f
          docker volume prune -f

      - name: Install pigz
        run: sudo apt-get install -y pigz  # 安装多线程压缩工具

      - name: Process Images with Split
        run: |
          set -eo pipefail
          images="${{ github.event.inputs.docker_images }}"
          IFS=',' read -r -a image_array <<< "$images"
          
          output_dir="$GITHUB_WORKSPACE/docker-images"
          mkdir -p "$output_dir"

          # 生成合并说明
          echo "使用方法: cat *.part.* > full.tar.gz" > "$output_dir/README.txt"

          for image in "${image_array[@]}"; do
            echo "==== 处理镜像: $image ===="
            docker pull --platform linux/amd64 "$image"
            
            safe_name=$(echo "$image" | sed 's/[^a-zA-Z0-9._-]/_/g')
            docker save "$image" | \
            pigz -9 | \
            split -d -b 1800M - "$output_dir/${safe_name}-amd64.tar.gz.part."

            docker rmi "$image"
          done

      - name: Upload Split Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: split-docker-images
          path: |
            docker-images/*
          retention-days: 1
